spring:
  datasource:
    url: "jdbc:h2:mem:personal-expenses-db"
    username: "root"
    password: "root"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    open-in-view: true
exchange:
  rates:
      url: "https://api.exchangerate.host/latest?base="